- name: odoo pre-tasks
  hosts: odoo-test
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson

- name: odoo main
  hosts: odoo-test
  gather_facts: yes
  roles:
    - ANXS.postgresql
    - sebalix.odoo
  vars:
    - postgresql_version: 9.3
    - odoo_version: 9.0
    - odoo_config_unaccent: True
