- name: odoo
  hosts: odoo-test
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson
  roles:
    - ANXS.postgresql
  vars:
    - postgresql_version: 9.3
