- name: odoo pre-tasks
  hosts: odoo-test
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson

- name: odoo main
  hosts: odoo-test
  gather_facts: yes
  roles:
    - ANXS.postgresql
    - sebalix.odoo
  vars:
    - postgresql_version: 9.3
    - odoo_version: 9.0
    - odoo_config_unaccent: True

- name: odoo nginx
  hosts: odoo-test
  tasks:
    - name: Set hostname
      hostname: name=odoo.studio38.de

    - name: Install system packages
      apt: pkg={{ item }} update-cache=yes
      with_items:
        - nginx

    - name: Set timezone variables
      copy: content='Europe/Berlin\n'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone

    - name: remove default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: copy nginx config
      template: src=files/nginx.conf.j2 dest=/etc/nginx/sites-enabled/odoo.conf
      notify:
      - restart nginx

    - name: make sure nginx server is running
      service: name=nginx state=started enabled=yes

  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

    - name: restart nginx
      service: name=nginx state=restarted
